spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blps
    username: postgres
    password: password

  jpa.generate-ddl: true

  activemq:
    broker-url: tcp://80.242.57.251:61616
    user: admin
    password: admin

server.port: 8081

camunda.bpm.admin-user:
  id: admin
  password: admin